"""CSV / PDF 导出器.

CSV: 每次都生成 (零依赖), 作为邮件附件.
PDF: 需要 fpdf2 库, 没装时返回 None (邮件里不加 PDF 附件, 其他一切照常).
"""
from __future__ import annotations

import csv
import io
import logging
import os
from typing import Sequence

from .ranker import RankedItem

logger = logging.getLogger(__name__)


# ====================== CSV ======================

CSV_FIELDS = [
    "rank", "title", "price_usd", "source", "category",
    "rank_change", "is_new", "url", "asin", "badges", "selling_point",
]


def export_csv(items: Sequence[RankedItem], date_str: str) -> str:
    """生成 CSV 字符串, 返回 UTF-8 BOM 编码的内容 (Excel 友好)."""
    buf = io.StringIO()
    # 写 UTF-8 BOM, 让 Excel 自动识别编码
    buf.write("\ufeff")
    writer = csv.DictWriter(buf, fieldnames=CSV_FIELDS)
    writer.writeheader()
    for i, r in enumerate(items, start=1):
        writer.writerow({
            "rank": i,
            "title": r.title,
            "price_usd": f"{r.price_usd:.2f}",
            "source": r.source,
            "category": r.category,
            "rank_change": f"+{r.rank_change}" if r.rank_change > 0 else str(r.rank_change),
            "is_new": "YES" if r.is_new else "",
            "url": r.url,
            "asin": r.asin,
            "badges": " | ".join(r.badges),
            "selling_point": r.selling_point,
        })
    return buf.getvalue()


def csv_bytes(items: Sequence[RankedItem], date_str: str) -> bytes:
    """返回 CSV 的 UTF-8 bytes, 适合做邮件附件."""
    return export_csv(items, date_str).encode("utf-8")


# ====================== PDF ======================

def _has_fpdf() -> bool:
    try:
        import fpdf  # noqa: F401
        return True
    except ImportError:
        return False


def _safe_pdf_text(text: str) -> str:
    """去掉 emoji 和非 latin-1 字符, 防止 fpdf2 报错."""
    import re
    # 去掉 emoji (Unicode 范围)
    text = re.sub(r'[\U0001F000-\U0001FFFF]', '', text)
    text = re.sub(r'[\u2600-\u27BF]', '', text)
    text = re.sub(r'[\uFE00-\uFE0F]', '', text)
    text = re.sub(r'[\u200D]', '', text)
    # 只保留 latin-1 可打印字符
    return text.encode('latin-1', errors='ignore').decode('latin-1')


def export_pdf(
    items: Sequence[RankedItem],
    date_str: str,
    title: str = "Daily Trending Report",
) -> bytes | None:
    """生成 PDF 报告. 没有 fpdf2 时返回 None.

    PDF 内容:
      - 标题 + 日期
      - Top 10 商品表格 (排名/标题/价格/来源/异常标签)
      - 图例 (异常标签含义)
    """
    if not _has_fpdf():
        logger.info("fpdf2 not installed, skip PDF generation")
        return None

    from fpdf import FPDF

    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=15)

    # --- 封面 / 标题 ---
    pdf.add_page()
    pdf.set_font("Helvetica", "B", 20)
    pdf.cell(0, 12, _safe_pdf_text(title), ln=True, align="C")
    pdf.set_font("Helvetica", "", 12)
    pdf.cell(0, 8, f"Date: {date_str}  |  Market: US  |  Price <= $20", ln=True, align="C")
    pdf.ln(6)

    # --- Top N 表格 ---
    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(0, 10, f"Top {len(items)} Rising Products", ln=True)
    pdf.ln(2)

    # 表头
    col_widths = [12, 70, 18, 22, 25, 20, 23]  # rank, title, price, source, category, change, badges
    headers = ["#", "Title", "Price", "Source", "Category", "Change", "Badges"]
    pdf.set_font("Helvetica", "B", 9)
    pdf.set_fill_color(240, 240, 240)
    for w, h in zip(col_widths, headers):
        pdf.cell(w, 7, h, border=1, fill=True, align="C")
    pdf.ln()

    # 数据行
    pdf.set_font("Helvetica", "", 8)
    for i, r in enumerate(items, start=1):
        badges_short = " ".join(r.badges[:2]) if r.badges else "-"
        change_str = f"+{r.rank_change}" if r.rank_change > 0 else str(r.rank_change)
        row = [
            str(i),
            _safe_pdf_text(r.title[:40]),
            f"${r.price_usd:.2f}",
            r.source[:10],
            _safe_pdf_text(r.category[:14]),
            change_str,
            _safe_pdf_text(badges_short[:14]),
        ]
        for w, val in zip(col_widths, row):
            pdf.cell(w, 6, val, border=1)
        pdf.ln()

    # --- 图例 ---
    pdf.ln(6)
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(0, 8, "Badge Legend", ln=True)
    pdf.set_font("Helvetica", "", 9)
    legends = [
        ("FLASH", "One-night wonder: #50+ to top 10 overnight"),
        ("HOT", "Rank surged: +30 or more in one day"),
        ("LAUNCH", "First-time entry with price info"),
        ("STREAK", "Rising 3+ consecutive days"),
        ("DROP", "Price dropped 30%+ below historical low"),
        ("HIKE", "Price jumped 30%+ above historical high"),
        ("DOWN", "Rank dropped 20+ in one day"),
    ]
    for code, desc in legends:
        pdf.cell(18, 5, code, ln=False)
        pdf.cell(0, 5, desc, ln=True)

    # --- 底部 ---
    pdf.ln(8)
    pdf.set_font("Helvetica", "I", 8)
    pdf.cell(0, 5, "Generated by Daily Trending Bot | Amazon + eBay + Google Trends + TikTok", ln=True, align="C")

    return pdf.output()


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")

    # 造点假数据演示
    fake = [
        RankedItem(
            title="Cute Cat Earphone Case", price_usd=8.99,
            url="https://amazon.com/dp/B0A", image_url="",
            source="amazon", category="Phone Accessories",
            rank_today=1, rank_yesterday=50, rank_change=49,
            is_new=False, asin="B0A",
            selling_point="925 silver needle, hypoallergenic",
            badges=["🔥 HOT", "⚡ FLASH"],
        ),
        RankedItem(
            title="Beaded Bracelet Set", price_usd=12.50,
            url="https://tiktok.com/x", image_url="",
            source="tiktok", category="Jewelry",
            rank_today=2, rank_yesterday=None, rank_change=50,
            is_new=True, asin="B0B",
            selling_point="natural stone, multi-layer",
            badges=["🚀 LAUNCH"],
        ),
    ]

    # CSV
    csv_data = csv_bytes(fake, "2026-06-05")
    print(f"CSV: {len(csv_data)} bytes")
    print(csv_data.decode("utf-8")[:300])
    print("...")

    # PDF
    pdf_data = export_pdf(fake, "2026-06-05")
    if pdf_data:
        print(f"PDF: {len(pdf_data)} bytes")
        with open("output/test_report.pdf", "wb") as f:
            f.write(pdf_data)
        print("PDF saved to output/test_report.pdf")
    else:
        print("PDF skipped (fpdf2 not installed)")
